apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snora.fullname" . }}
  labels:
    {{- include "snora.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- if .Values.secrets.redisPassword }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- end }}
